name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: cargo test --features=fail-on-warnings --verbose
      - name: Build on stable Rust
        run: cargo +stable build
      - name: Clippy
        run: cargo clippy
      - name: Check formatting
        run: cargo fmt -- --check
      - name: Make documentation
        run: cargo doc --verbose
